clear
TestFile_path = 'MainTest.mldatx';
result = sltest.testmanager.load(TestFile_path);
resultset = sltest.testmanager.run;
tfr = getTestFileResults(resultset);

reportFilePath = 'TestReport20.pdf';

sltest.testmanager.report(tfr,reportFilePath,...
    'Author','Jeegar',...
    'Title','Test of mine',...
    'IncludeMLVersion',true,...
    'IncludeTestResults',int32(0),...
    'IncludeSimulationSignalPlots',true,...
    'NumPlotColumnsPerPage',2,...
    'LaunchReport',false);

sltest.testmanager.clearResults;
sltest.testmanager.clear;

